config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  constraints(AdminDomainConstraint.new) do
    scope module: 'admin' do
      devise_for :users,
                 controllers: { sessions: 'admin/sessions' },
                 skip: %i[registrations passwords confirmations unlocks], as: :admin
      resources :organizations do
        resources :members
      end
      resources :officer_positions
      resources :students
      resources :admins
      resources :elections
      resources :party_lists
      resources :candidates

      root to: 'home#index', as: :admin_root
    end
  end

  constraints(StudentDomainConstraint.new) do
    devise_for :users,
               controllers: {
                 sessions: 'students/sessions',
                 registrations: 'students/registrations',
                 passwords: 'students/passwords'
               }

    root to: 'students/home#index', as: :student_root
  end
end

app/views/admin/admins/_form.html.erb
<div class="form-container">
  <h1><%= action_name.capitalize %> Admin</h1>

  <div class="mb-4">
    <%= link_to 'Back to Lists', admins_path, class: 'inline-block px-3 py-1 bg-blue-600 text-white text-sm rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500' %>
  </div>

  <%= form_with model: @admin, url: url, method: method, html: { class: 'w-full' } do |form| %>
    <div class="mb-4">
      <%= form.label :email, class: 'form-label' %>
      <%= form.email_field :email, class: 'mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring-blue-500 p-2' %>
    </div>

    <div class="mb-4">
      <%= form.label :username, class: 'form-label' %>
      <%= form.text_field :username, class: 'mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring-blue-500 p-2' %>
    </div>

    <div class="mb-4 text-gray-700">
      <p>The default password is <strong>qwer4321`</strong></p>
    </div>

    <div>
      <%= form.submit submit, class: 'w-full bg-blue-600 text-white py-2 text-sm rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500' %>
    </div>
  <% end %>
</div>

app/views/admin/admins/edit.html.erb
<%= render partial: 'form', locals: { url: admin_path(@admin), submit: 'Create', method: :patch } %>

app/views/admin/admins/index.html.erb
<div class="form-container">
  <h1>Admin Lists</h1>

  <div class="mb-4">
    <%= link_to 'Add Admin', new_admin_path, class: 'inline-block px-3 py-1 bg-blue-600 text-white text-sm rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500' %>
  </div>

  <div class="space-y-4">
    <% @admins.each do |admin| %>
      <div class="p-4 bg-white rounded-lg shadow">
        <div class="flex justify-between items-center">
          <p class="text-xl font-semibold text-gray-800 mb-2">Email: <span><%= admin.email %></span></p>

          <div class="relative group" data-controller="dropdown">
            <button class="inline-block px-3 py-1 text-sm border border-b rounded-md hover:bg-white focus:outline-none focus:ring-2 focus:ring-white" data-action="click->dropdown#toggle">
              <%= image_tag("admin/setting.svg", alt: "Setting Icon") %>
            </button>

            <div data-dropdown-target="dropdown" class="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg hidden">
              <%= link_to 'Edit', edit_admin_path(admin), class: 'block px-4 py-2 text-sm text-yellow-600 hover:bg-yellow-50' %>
              <%= link_to 'Remove', admin_path(admin),
                          data: {
                            action: 'click->sweet-alert#confirmDelete',
                            turbo_method: :delete
                          },
                          class: 'block px-4 py-2 text-sm text-red-600 hover:bg-red-50' %>
            </div>
          </div>
        </div>
        <p class="text-gray-600 mb-2">Username: <span><%= admin.username %></span></p>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/admins/new.html.erb
<%= render partial: 'form', locals: { url: admins_path, submit: 'Create', method: :post } %>